name: Lint_and_Test

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: intsall
        run: yarn

      # Runs a single command using the runners shell
      - name: lint
        run: yarn lint

      # Runs a set of commands using the runners shell
      - name: unit test
        run: yarn test --coverage
      - name: Coveralls GitHub Action
      # You may pin to the exact commit or the version.
      # uses: coverallsapp/github-action@8cbef1dea373ebce56de0a14c68d6267baa10b44
        uses: coverallsapp/github-action@v1.1.2
        with:
          # 
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # Path to lcov file
          path-to-lcov: ./coverage/lcov.info
          # Job flag name, e.g. "Unit", "Functional", or "Integration". Will be shown in the Coveralls UI.
          flag-name: unit
